apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: order-agent

resources:
  - k8s/00-namespace.yaml
  - k8s/01-configmap.yaml
  - k8s/02-postgres.yaml
  - k8s/03-backend.yaml
  - k8s/04-staff-frontend.yaml
  - k8s/05-customer-frontend.yaml
